name: Python CI

on:
  push:
  pull_request:


jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

    with:
      PYTHON_VERSION: "3.13"
      USE_PYLINT: true
      USE_RUFF: true
      BUILD_PACKAGE: true
      GENERATE_DOCUMENTATION: true
      USE_SEMANTIC_RELEASE: false
      EXECUTE_TESTS: true
      EXECUTE_COVERAGE_TEST: true
      EXTRA_REQUIREMENTS: '[report]'
      PYTHON_PACKAGE_NAME: 'teaser'