name: Python CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    with:
      PYTHON_VERSION: "3.10"
      USE_PYLINT: true
      USE_RUFF: true
      BUILD_PACKAGE: true
      GENERATE_DOCUMENTATION: true
      EXECUTE_TESTS: true
      EXECUTE_COVERAGE_TEST: true
      EXTRA_REQUIREMENTS: '[report]'
